
variables:
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: step_flow_test

services:
  - postgres:12.2-alpine
  - rabbitmq:3.8.14-alpine

include: 
  - project: 'media-cloud-ai/ci/pipelines'
    file: 'elixir/elixir-base.yml'
