dist: focal

language: elixir

sudo: required

elixir:
  - 1.10.0
  - 1.10.1
  - 1.10.2
  - 1.11.0
  - 1.11.1
  - 1.11.2
  - 1.11.3
otp_release:
  - 22.3
  - 23.0

env:
  - MIX_ENV=test

services:
  - postgresql

addons:
  apt:
    packages:
    - rabbitmq-server

matrix:
  include:
    # Elixir format
    - elixir: 1.11.3
      script:
        - mix format --check-formatted
      env: CHECK_FORMAT=TRUE
    # Elixir credo
    - elixir: 1.11.3
      script:
        - mix credo --strict
      env: CHECK_SYNTAX=TRUE
    # Elixir coveralls
    - elixir: 1.11.3
      script:
        - MIX_ENV=test mix coveralls.travis
      env: COVERALLS=TRUE

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - psql -c 'create database step_flow_test;' -U postgres

script:
  - mix compile
  - mix test
